### ISSUE TITLE
Certain results layers return more than just their own results

### ISSUE THREAD

**Issue by jacobdadams** [agrc/raster#42]
Several layers return links for a bunch of other layers as well, almost as if there's a definition query that wasn't set on the index layer. So far, I've seen it in these layers in Salt Lake valley:

1.25m Bare Earth DEM
1m raw XYZ
1m first return
1m last return
1m bare Earth
1m bare earth

The results for each one displays the links for all six categories. These are all derived from the fall 2006 project and are delivered as .asc files (ASCII). 

Steps to reproduce:

1. Select LiDAR DEMs
1. Place a point in the center of the I-15/I-215 south interchange.
1. Expand any of the results under the 1.25 Meter, 1 Meter, or 2 Meter options
1. Click the blue Download link.
1. The Download Data step presents six downloads for the single tile

![image](https://user-images.githubusercontent.com/38168030/77450145-80c49b80-6db8-11ea-8c4e-53aee965cd57.png)

**Comment by rkelson** [comment]
yeah that is interesting that it is working like that. I think I may have only looked at _Results_ and not the _Download Data_ after the change was made but not positive. Here is a little background:

- the 2006 lidar was delivered in multiple resolutions with tile indices that overlap
- when I reworked some things I appended all the tile indices into one _LiDAR2006_Tiles_ index
- _LiDAR_Extents_ has a field Tile_Index that points to _LiDAR2006_Tiles_ for this 2006 collection and no longer to the 12 individual tile indices
- There are other datasets that have overlapping tile indices but none as complex as this collection with multiple resolutions & products.

Below are the main fields the app uses to query.  I need to go and look at the notes I have for how the app does what it does but I think I can change what is in the {} in the Category field to fix this issue but maybe  @stdavis has some ideas.
![image](https://user-images.githubusercontent.com/6200941/77455855-0435bb00-6dc0-11ea-8cfa-143fe96c13ae.png)

**Comment by stdavis** [comment]
Here's the query that the app makes to get the tiles: https://raster.utah.gov/arcgis/rest/services/Raster/MapServer/115/query?f=html&returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=%7B%22x%22%3A-12457181.619585762%2C%22y%22%3A4958766.71814634%2C%22spatialReference%22%3A%7B%22wkid%22%3A3857%7D%7D&geometryType=esriGeometryPoint&inSR=3857&outFields=*&outSR=3857

It does not add any definition query. It just queries the `LiDAR2006_Tiles` feature class. I'm guessing that I'll need to add some code to add a def query for this...

**Comment by rkelson** [comment]
I could switch it back to using 12 tile indices but then they would have to be added back to the .mxd. Probably worth investigating an addition to the code

**Comment by stdavis** [comment]
I've got this on my Trello, but it might be days before I get to it...

**Comment by rkelson** [comment]
Well aren't you fancy.... Yeah when you are looking for a new problem to solve see if you are interested in revising the code. Otherwise I will look at merging some of the tile indices and reduce the 12 down to 6. I blame this problem on Jeanie.

**Comment by stdavis** [comment]
I took a closer look at the code related to this issue. I'm not sure that the data supports this fix completely. I can see the resolution field which seems to map to the resolution field in the extents layer, but there's nothing in the tile index layer for the product (first return, last return, etc):
![image](https://user-images.githubusercontent.com/1326248/80520171-42d20e80-8946-11ea-88d4-cd845fdba666.png)

This would also require significant changes to the code because the app was built on the assumption that each product has a separate tile index layer. With that being said, I think that this was a design mistake and would love to get to the point where it can handle all of the tiles being in a single layer (or a small group of layers). But this would take some major changes to the data and to the application. I would vote that the data be put back to single index layers and I'll update the map service to accommodate for now and we can talk about this enhancement when the app is rebuilt in the future.

**Comment by stdavis** [comment]
@rkelson What are you thoughts about my last comment?

**Comment by stdavis** [comment]
@rkelson Do you have any thoughts/direction on this issue?

**Comment by rkelson** [comment]
I'll put it on the list to change it back to how it was before we did the big storage change and reorganization. It would be cool if tile indices could be merged into single layers by project but I understand there is a lot that would need to change in the code.
